language: node_js
sudo: required 
dist: trusty
node_js:
  - "node"
cache:
  directories:
    - "$HOME/.npm"
before_install:
  - sudo apt-get update
  - sudo apt install -y xsel
script:
  - npm run build
  - npm run ci
